export const API_ENDPOINTS = {
  HEALTH: '/health',
  AMPEL: {
    LATEST: '/ampel/latest',
    HISTORY: (limit = 10) => `/ampel/history?limit=${limit}`,
    THESES: '/ampel/theses',
    THESES_RESOLVED: '/ampel/theses/resolved',
    UPDATE_THESIS: (id: string) => `/ampel/theses/${id}`,
    EXTRACT_LESSONS: (id: string) => `/ampel/theses/${id}/extract-lessons`,
    REFINE_THESIS: '/ampel/theses/refine',
    PROMPTS: '/ampel/prompts',
    RUN: '/ampel/run',
    POSITIONS: '/ampel/positions',
    CREATE_POSITION: '/ampel/positions',
    CLOSE_POSITION: (id: string) => `/ampel/positions/${id}/close`,
    DELETE_POSITION: (id: string) => `/ampel/positions/${id}`,
  },
  SEARCH: '/ampel/embeddings/search-all',
  KNOWLEDGE_ASK: '/ampel/knowledge/ask',
  PRICES: {
    WATCHLIST: '/prices/watchlist',
    ADD_WATCHLIST: '/prices/watchlist',
    REMOVE_WATCHLIST: (ticker: string) => `/prices/watchlist/${ticker}`,
    TICKER: (ticker: string, days = 30) => `/prices/${ticker}?days=${days}`,
    ANALYST_RATINGS: (ticker: string) => `/prices/analyst-ratings/${ticker}`,
    ANALYST_RATINGS_HISTORY: (ticker: string) => `/prices/analyst-ratings/${ticker}/history`,
    ANALYST_RATINGS_SYNC: '/prices/analyst-ratings/sync',
    ASSET_NEWS: (ticker: string) => `/prices/asset-news/${ticker}`,
    ANALYST_NEWS: (ticker: string) => `/prices/analyst-news/${ticker}`,
    ANALYST_NEWS_SYNC: '/prices/analyst-news/sync',
    SYNC: '/prices/sync',
  },
  CHAT: '/chat/',
  CHAT_STREAM: '/chat/stream',
  RESEARCH: {
    LIST: '/research/',
    DETAIL: (id: string) => `/research/${id}`,
    CREATE: '/research/',
    UPDATE: (id: string) => `/research/${id}`,
    RUN: (id: string) => `/research/${id}/run`,
    DELETE: (id: string) => `/research/${id}`,
    GENERATE_PROMPT: '/research/generate-prompt',
    REFINE_PROMPT: '/research/refine-prompt',
  },
  NEWS: {
    LIST: '/news/topics',
    DETAIL: (id: string) => `/news/topics/${id}`,
    CREATE: '/news/topics',
    UPDATE: (id: string) => `/news/topics/${id}`,
    DELETE: (id: string) => `/news/topics/${id}`,
    RUN: (id: string) => `/news/topics/${id}/run`,
    RUN_ALL: '/news/run-all',
    RESULTS: (slug: string, limit = 10) => `/news/results/${slug}?limit=${limit}`,
    LATEST: '/news/latest',
    GENERATE_PROMPT: '/news/generate-prompt',
    REFINE_PROMPT: '/news/refine-prompt',
    SUGGEST_FEEDS: '/news/suggest-feeds',
  },
  SCANNER: {
    RUN: '/scanner/run',
    LATEST: '/scanner/latest',
    HISTORY: (limit = 10) => `/scanner/history?limit=${limit}`,
  },
} as const
