export const API_ENDPOINTS = {
  HEALTH: '/health',
  AMPEL: {
    LATEST: '/ampel/latest',
    HISTORY: (limit = 10) => `/ampel/history?limit=${limit}`,
    THESES: '/ampel/theses',
    UPDATE_THESIS: (id: string) => `/ampel/theses/${id}`,
    REFINE_THESIS: '/ampel/theses/refine',
    PROMPTS: '/ampel/prompts',
  },
  PRICES: {
    WATCHLIST: '/prices/watchlist',
    TICKER: (ticker: string, days = 30) => `/prices/${ticker}?days=${days}`,
    SYNC: '/prices/sync',
  },
  CHAT: '/chat/',
  CHAT_STREAM: '/chat/stream',
  RESEARCH: {
    LIST: '/research/',
    DETAIL: (id: string) => `/research/${id}`,
    CREATE: '/research/',
    UPDATE: (id: string) => `/research/${id}`,
    RUN: (id: string) => `/research/${id}/run`,
    DELETE: (id: string) => `/research/${id}`,
    GENERATE_PROMPT: '/research/generate-prompt',
    REFINE_PROMPT: '/research/refine-prompt',
  },
  NEWS: {
    LIST: '/news/topics',
    DETAIL: (id: string) => `/news/topics/${id}`,
    CREATE: '/news/topics',
    UPDATE: (id: string) => `/news/topics/${id}`,
    DELETE: (id: string) => `/news/topics/${id}`,
    RUN: (id: string) => `/news/topics/${id}/run`,
    RUN_ALL: '/news/run-all',
    RESULTS: (slug: string, limit = 10) => `/news/results/${slug}?limit=${limit}`,
    LATEST: '/news/latest',
    GENERATE_PROMPT: '/news/generate-prompt',
    REFINE_PROMPT: '/news/refine-prompt',
  },
} as const
